# Generated by Django 3.1.1 on 2020-09-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0009_formsetmodelform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSetModelForm',
        ),
    ]
